# Generated by Django 4.0.3 on 2022-04-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='airfield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airfield_name', models.CharField(max_length=150)),
                ('airfield_cityname', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plane', models.CharField(max_length=100)),
                ('volume', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='fly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_start', models.CharField(max_length=200)),
                ('airfield_start', models.CharField(max_length=150)),
                ('destination_city', models.CharField(max_length=200)),
                ('destination_airfield', models.CharField(max_length=150)),
                ('d_time', models.DateTimeField()),
                ('price', models.FloatField()),
                ('transport', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('company', models.CharField(max_length=100)),
            ],
        ),
    ]
